### ISSUE TITLE
BCR-tutorial

### ISSUE THREAD

**Issue by grst** [scverse/scirpy#199]
Add a tutorial for BCR (or joint BCR/TCR analysis). 

Either as additional tutorial, or replace the TCR tutorial as the main "getting started" tutorial. 

The latter may make particularly sense, as we could show a joint BCR/TCR analysis.

**Comment by ktpolanski** [comment]
Another signal boost post. I just tried to analyse some BCR, so I mimicked the TCR tutorial.

**Comment by grst** [comment]
Hi @ktpolanski, 

the main reason why I didn't prioritize the tutorial so far is that the analysis steps don't differ a lot between TCR and BCR... So following the TCR tutorial should be fine. Would still be nice to have it covered, of course. 

Do you have something particular in mind with respect to BCRs? 

Best, 
Gregor

**Comment by ktpolanski** [comment]
Having had a chat with a biologist, I believe Scirpy's existing functionality covers BCR-specific phenomena (non-identity CDR3 comparisons for somatic hypermutation, and `.obs['..._c_gene']` for class-switch recombination). As such, it should actually be fine, yeah!

Given how vital a role the neighbour/clonotype calling seems to have in the process, do you have any suggestions for Levenshtein parameterisation for BCRs?

**Comment by grst** [comment]
We don't have any evidence, what the optional threshold is. For TCR, I would say that anything with a levenshtein distance of >1-2 is unlikely to recognize the same antigen. @szabogtamas, our immunology expert, suggested that for BCR it may make sense to relax this threshold a bit. 

In the introduction of [this preprint](https://www.biorxiv.org/content/10.1101/2020.03.30.017384v1.full), they write: 

> The authors in [14], have noticed that the distribution of distances between sequences and their nearest neighbors (distance-to-nearest) tends to be bi-modal, with a first mode corresponding to clonally related sequences and second mode corresponding to sequences without clonal relationship (singletons). Using this bi-modality, [14] proposes to set a threshold that separates the two modes. Following this observation, [1, 17] use the bi-modality of this distribution to suggest an automatic way to set the threshold. A recent method by [2] uses spectral clustering with an adaptive threshold to identify the groups of clonally related sequences.


I [gave that a quick shot](https://gist.github.com/grst/42c539c91e665effdb71e7c494c05e46) with the [Maynard 2020](https://icbi-lab.github.io/scirpy/generated/scirpy.datasets.maynard2020.html) dataset, and coudn't find a bimodal distribution. However, the number of B-cells in that dataset is rather small (~1,700), so it might very well be that this pattern only starts to emerge with 10,000s or even 100,000s of cells. 

In any case, this is a topic that interests me myself. If you find something useful, let me know and I'm happy to add it to the documentation.
