### ISSUE TITLE
error when access to scirpy document

### ISSUE THREAD

**Issue by johnsnowgo** [scverse/scirpy#323]
Hello! 
Thanks a lot for creating this fantastic tools to analyze VDJ data.
I recently tried to access the scirpy docunment, but there always is an error for 'icbi-lab.github.io refused our connection request'. Is the website being maintained?  When can I access the document. I sincerely hope you can continue to improve this package. Thanks again. 

Best.

**Comment by grst** [comment]
Hi @johnsnowgo, 

what page exactly are you trying to access? The documentation is at https://icbi-lab.github.io/scirpy/latest/ and works fine for me.

**Comment by johnsnowgo** [comment]
> Hi @johnsnowgo,
> 
> what page exactly are you trying to access? The documentation is at https://icbi-lab.github.io/scirpy/latest/ and works fine for me.

The same as you. It's really strange but I can access to it now.  Thanks a lot.
