### ISSUE TITLE
BD Rhapsody data import

### ISSUE THREAD

**Issue by wajm** [scverse/scirpy#328]
I have a question about BD Rhapsody CDR3 VDJ data import.
Following scirpy introduction, imported data object is very similar with BD VDJ data.

If you have an interest wiht BD VDJ data, please check the possibility of BD VDJ data import into scirpy.
I can share my data to you.

**Comment by grst** [comment]
Hi @wajm, 

I'm definitely interested to have a data loader for BD data! 

Would you be interested to wrap your code into a function and make a Pull-request to the [`io` module](https://github.com/scverse/scirpy/blob/master/scirpy/io/_io.py)? 

Also pinging @Raphael-Gronauer who I think looked into this at some point. 

Best,
Gregor

**Comment by wajm** [comment]
Hi Gregor,
Thank you for quick response.
Actually, I'm not a expert for computational work (just an end-user).
https://pubmed.ncbi.nlm.nih.gov/34003804/
Following the JCI study, I make around 80 human nasal immune cells and PBMC VDJ libraries.
I'd like to use scirpy for BD Rhapsody VDJ data. (import the data to scirpy and analyze them) 

best, 
JUNGMO

**Comment by grst** [comment]
ah, sorry, I understood you already had some custom code based on the [io tutorial](https://scverse.org/scirpy/latest/tutorials/tutorial_io.html). 

Let's see if @Raphael-Gronauer has some code to offer ;)

**Comment by wajm** [comment]
Okay~ @Raphael-Gronauer
Please let me know where can I share my example data.

**Comment by Raphael-Gronauer** [comment]
I have implemented a the BD data import and created a pull request.
The code just needs to be reviewed by @grst

**Comment by wajm** [comment]
Hi, @Raphael-Gronauer.
Thank you very much.
You have BD example data? I add my BD VDJ data.
[RhapVDJ.csv](https://github.com/scverse/scirpy/files/8348480/RhapVDJ.csv)
best,
JungMo

**Comment by Raphael-Gronauer** [comment]
@wajm 
thanks 
I have BD data from my own project.

**Comment by wajm** [comment]
@Raphael-Gronauer.
Okay very good. 
I just inform to you my VDJ data is targeted immune panel.
I don't know this data form is similar with recent launched VDJ WTA version.
best,
JungMo

**Comment by Raphael-Gronauer** [comment]
@wajm 
I also work with a targeted panel.
The data import takes the data as it comes from the BD pipeline.
It needs one file for the RNAseq mols per cell and one file for the VDJ. (both as .csv)
Additional it is also possible to provide a .csv file for dCODE sequencing data if you have.

Best,
Raphael

**Comment by wajm** [comment]
@Raphael-Gronauer 
Perfect!!!
When the code is released, I will use it.
Thanks a lot.
Best,
JungMo

**Comment by wajm** [comment]
@grst @Raphael-Gronauer 
Please let me know when I can use the function.
best, 
JungMo

**Comment by grst** [comment]
Hi @wajm, 

sorry for the delay. I'm right now looking into wrapping up what Raphael put together. 

I noticed that there are two possible output files that contain the VDJ data (`_perCell` and `_Dominant_Contigs`). The BD demo data contains all these files
```
-rw-r--r-- 1 sturm sturm 8.2M Jan 10 02:02 RhapVDJDemo-BCR_VDJ_Dominant_Contigs.csv
-rw-r--r-- 1 sturm sturm 4.1K Jan 10 02:02 RhapVDJDemo-BCR_VDJ_metrics.csv
-rw-r--r-- 1 sturm sturm 448K Jan 10 02:02 RhapVDJDemo-BCR_VDJ_perCell.csv
-rw-r--r-- 1 sturm sturm 2.7M Jan 10 02:02 RhapVDJDemo-BCR_VDJ_perCell_uncorrected.csv
-rw-r--r-- 1 sturm sturm 128M Jan 10 02:02 RhapVDJDemo-BCR_VDJ_Unfiltered_Contigs.csv
```

Do you have the same files available?

**Comment by wajm** [comment]
Hi, @grst
Thank you for respond.
I've checked but my demo project from BD is a little bit different.
I'll ask to these to them.
best,
JungMo

**Comment by grst** [comment]
@wajm, any chance you could share your dataset with me? My e-mail address is in my github profile, if you prefer to do so privately.

**Comment by wajm** [comment]
@grst ,
Do you mean the upper demo data or others? Anything I will send to your e-mail in tomorrow.
Thanks.

**Comment by grst** [comment]
@wajm, I mean the dataset you want to load with scirpy.

**Comment by wajm** [comment]
@grst,
I'm sorry but SevenBridge is under maintenance.
Please wait a moment.

**Comment by grst** [comment]
Hi all, 

the feature is now available from the master branch. A release will follow soon. You can install the development version with
```
pip install git+https://github.com/scverse/scirpy.git@master
```

Happy about feedback!
