### ISSUE TITLE
how to read 10 sample generated by 10X cellranger

### ISSUE THREAD

**Issue by honghh2018** [scverse/scirpy#331]
Hi developer,
     how can i read 10 sample of TCR data simultaneously generated by 10X cellranger  using the scirpy.io.read_10x_vdj function, and then automatically merge into one anndata object?
     Any advice would be appreciated.

Best,
honghanhui

**Comment by honghh2018** [comment]
Had any one hear this issue?

**Comment by grst** [comment]
Hi,

There's a section in the tutorials about this:
https://scverse.org/scirpy/latest/tutorials/tutorial_io.html#Combining-multiple-samples

Does that help?

Best,
Gregor

**Comment by honghh2018** [comment]
您好！已经收到邮件，祝好！                                    洪汉辉

**Comment by honghh2018** [comment]
Thanks @grst,
      The reply very helpful for me
Best

**Comment by honghh2018** [comment]
Unfortunately,
I follow your vignette, using for loop to read all VDJ data generated by 10X cellranger vdj with expr matrix
The code lying below:
 adatas = []
for sample1 in all_samples:
    print(sample1)
    
    tcr_file = sample1
    n1 = sample1.split("/")[3]
    adata_tcr = ir.io.read_10x_vdj(tcr_file)
    adata_tcr.obs["sample"] = n1
    adatas.append(adata_tcr)


      I get another issue when i was running at 
step:
     ir.pp.ir_dist(adata)
    ir.tl.define_clonotypes(adata, receptor_arms="all", dual_ir="primary_only")
 

Computing sequence x sequence distance matrix for VJ sequences.
Computing sequence x sequence distance matrix for VDJ sequences.
Initializing lookup tables. 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [81], in <cell line: 2>()
      1 ir.pp.ir_dist(adata)
----> 2 ir.tl.define_clonotypes(adata, receptor_arms="all", dual_ir="primary_only")

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/io/_util.py:67, in _check_upgrade_schema.<locals>.check_upgrade_schema_decorator.<locals>.check_wrapper(*args, **kwargs)
     65 for i in check_args:
     66     _check_anndata_upgrade_schema(args[i])
---> 67 return f(*args, **kwargs)

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/tl/_clonotypes.py:399, in define_clonotypes(adata, key_added, distance_key, **kwargs)
    393     logging.info(
    394         "ir_dist for sequence='nt' and metric='identity' not found. "
    395         "Computing with default parameters."
    396     )  # type: ignore
    397     ir_dist(adata, metric="identity", sequence="nt", key_added=distance_key)
--> 399 return define_clonotype_clusters(
    400     adata,
    401     key_added=key_added,
    402     sequence="nt",
    403     metric="identity",
    404     partitions="connected",
    405     **kwargs,
    406 )

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/io/_util.py:67, in _check_upgrade_schema.<locals>.check_upgrade_schema_decorator.<locals>.check_wrapper(*args, **kwargs)
     65 for i in check_args:
     66     _check_anndata_upgrade_schema(args[i])
---> 67 return f(*args, **kwargs)

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/tl/_clonotypes.py:287, in define_clonotype_clusters(adata, sequence, metric, receptor_arms, dual_ir, same_v_gene, within_group, key_added, partitions, resolution, n_iterations, distance_key, inplace, n_jobs, chunksize)
    216 """
    217 Define :term:`clonotype clusters<Clonotype cluster>`.
    218 
   (...)
    273 {return_values}
    274 """
    275 within_group, distance_key, key_added = _validate_parameters(
    276     adata,
    277     None,
   (...)
    284     key_added,
    285 )
--> 287 ctn = ClonotypeNeighbors(
    288     adata,
    289     receptor_arms=receptor_arms,
    290     dual_ir=dual_ir,
    291     same_v_gene=same_v_gene,
    292     match_columns=within_group,
    293     distance_key=distance_key,
    294     sequence_key="junction_aa" if sequence == "aa" else "junction",
    295     n_jobs=n_jobs,
    296     chunksize=chunksize,
    297 )
    298 clonotype_dist = ctn.compute_distances()
    299 g = igraph_from_sparse_matrix(clonotype_dist, matrix_type="distance")

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/ir_dist/_clonotype_neighbors.py:57, in ClonotypeNeighbors.__init__(self, adata, adata2, receptor_arms, dual_ir, same_v_gene, match_columns, distance_key, sequence_key, n_jobs, chunksize)
     54 # Initialize the DoubleLookupNeighborFinder and all lookup tables
     55 start = logging.info("Initializing lookup tables. ")  # type: ignore
---> 57 self.cell_indices, self.clonotypes = self._make_clonotype_table(adata)
     58 self._chain_count = self._make_chain_count(self.clonotypes)
     59 if adata2 is not None:

File /share/nas1/Data/software/mini_conda/Miniconda3/envs/python-immunologicalTools-scirpy/lib/python3.8/site-packages/scirpy/ir_dist/_clonotype_neighbors.py:75, in ClonotypeNeighbors._make_clonotype_table(self, adata)
     73 """Define 'preliminary' clonotypes based identical IR features."""
     74 if not adata.obs_names.is_unique:
---> 75     raise ValueError("Obs names need to be unique!")
     77 clonotype_cols = self._cdr3_cols + self._v_gene_cols
     78 if self.match_columns is not None:

ValueError: Obs names need to be unique!

Any advice would be appreciated
Best

hanhuihong

**Comment by honghh2018** [comment]
Had anyone hear this?

**Comment by honghh2018** [comment]
Had anyone hear this?

**Comment by grst** [comment]
Sorry for the late response. 

To concatenate anndata objects, your obs names (=cell barcodes) need to be unique. 
You can achieve that by calling `adata.obs_name_make_unique()`

For more information check the anndata documentation on concatenation: 
https://anndata.readthedocs.io/en/latest/concatenation.html
