### ISSUE TITLE
Exclusion of cells without immune receptor

### ISSUE THREAD

**Issue by CR-94** [scverse/scirpy#332]
Hi, thank you for developing scirpy; it is a great package!

I have a few questions regarding the exclusion of cells without IR / uncategorized cells (NaN) 

- According to the tutorial, in the line : `adata = adata[~adata.obs["chain_pairing"].isin(["orphan VDJ", "orphan VJ"]), :].copy()` we eliminate cells that don’t have at least a full pair of receptors. But, if I later plot `ax = ir.pl.group_abundance(adata, groupby="has_ir”)`, there are still some cells that don’t have an IR 
- Should the cells without an IR be excluded from the analysis (e.g., clonotype analysis, abundance)?

**Comment by grst** [comment]
Hi,


>    - According to the tutorial, in the line : adata =
>    adata[~adata.obs["chain_pairing"].isin(["orphan VDJ", "orphan VJ"]),
>    :].copy() we eliminate cells that don’t have at least a full pair of
>    receptors. But, if I later plot ax = ir.pl.group_abundance(adata,
>    groupby="has_ir”), there are still some cells that don’t have an IR
>    -
>
> Good point, it seems I oversimplified for the tutorial, which uses an
example dataset that only contains cells with IR.

There's also a "no IR" category to be filtered out. See
https://scverse.org/scirpy/latest/generated/scirpy.tl.chain_qc.html#scirpy.tl.chain_qc
for more details.

>
>    -
>    - Should the cells without an IR be excluded from the analysis (e.g.,
>    clonotype analysis, abundance)?
>
> It shouldn't really matter. Scirpy is designed in a way that it can handle
cells without IR (e.g. they would receive NaN as clonotype).
If your project is focused on IR, I would probably remove them. If also the
cells without IR are relevant for other analyses, I'd keep them.

Best,
Gregor

**Comment by grst** [comment]
HI @CR-94, 

I believe this has been answered. 
If not, or if you have any other questions, please ask them in the [scverse community forum](https://discourse.scverse.org/) which is our new place for help requests! 

Thanks, 
Gregor
