### ISSUE TITLE
Cannot convert output from Scirpy to dandelion

### ISSUE THREAD

**Issue by sbenjamaporn** [scverse/scirpy#343]
### Description of the bug

I try to convert the AnnData after clonal assignment by Scirpy into dandelion format. The result showed that "field productive has invalid bool T + T". I would like to convert it for updating germline sequence of each BCR sequences using dandelion because I did not find this function in Scirpy. However, if you could suggest the other ways. Feel free to let me know.

### Minimal reproducible example

```python
import scirpy as ir

ABC_irdata_exclude_orphan_dandelion = ir.io.to_dandelion(ABC_irdata_exclude_orphan)
ABC_irdata_exclude_orphan_dandelion
```

### The error message produced by the code above

```pytb
~/.conda/envs/dandelion/lib/python3.8/site-packages/airr/schema.py in validate_row(self, row)
    276                 if spec == 'number':  self.to_float(row[f], validate=True)
    277             except ValidationError as e:
--> 278                 raise ValidationError('field %s has %s' %(f, e))
    279 
    280         return True

ValidationError: field productive has invalid bool T + T
```

### Version information

<details>
<summary>versions</summary>

```

```

</details>

**Comment by grst** [comment]
Hi @sbenjamaporn, 

thanks for reporting this issue. 
I'm not yet sure what could be the problem. Could you please report the following: 

 * the entire stack trace of the error message (not just the last part as above) 
 * the result of `ABC_irdata_exclude_orphan.obs.columns`

Thanks, 
Gregor

**Comment by zktuong** [comment]
hi @grst @sbenjamaporn

I think it's got to do with a malformed entries in `productive` columns in the `adata.obs` that `airrCell` is getting. 

So @sbenjamaporn, can you check what's the unique values for:
scirpy's columns:
`['IR_VDJ_1_productive', 'IR_VDJ_2_productive', 'IR_VJ_1_productive', 'IR_VJ_2_productive']`
There shouldn't be any `T + T` in these

I think the following are dandelion's columns:
`['productive_VDJ', 'productive_VJ', 'productive', 'productive_summary']`
There would be `T + T` in these. But these columns would be ignored by `scirpy` when converting to an airr table?

I don't think `dandelion` use any of these columns when converting (it just refreshes based on the airr table that scirpy produces)

I wonder if the round trip of `scirpy` <-> `dandelion`  somehow got the columns confused?

**Comment by sbenjamaporn** [comment]
Dear @zktuong @grst 

Yes, ['IR_VDJ_1_productive', 'IR_VDJ_2_productive', 'IR_VJ_1_productive', 'IR_VJ_2_productive'] show only "TRUE or None" output. I agree with you about the convertion between them make it confuse. So, we could not convert scirpy result to dandelion, right?

**Comment by zktuong** [comment]
Hmm it looks like those additional productive columns are from dandelion. 

Can you try and remove every column from “clone_id_by_size” onwards and see if there’s still the issue of conversion?

**Comment by sbenjamaporn** [comment]
Dear @grst, 

Is there any ways that Scirpy could give full information as an AIRR standard ? ( I try ir.io.write_airr, but it did not create full information)

**Comment by sbenjamaporn** [comment]
@zktuong Thanks for suggestion, I will try!

**Comment by grst** [comment]
> Hmm it looks like those additional productive columns are from dandelion.

It seems the actual problem is in the conversion from dandelion to scirpy. @zktuong `ddl.to_scirpy` is just calling scirpy code?

> Is there any ways that Scirpy could give full information as an AIRR standard ? ( I try ir.io.write_airr, but it did not create full information)

Happy to discuss this. Could you please open a separate issue and describe what's missing?

**Comment by zktuong** [comment]
> It seems the actual problem is in the conversion from dandelion to scirpy. @zktuong `ddl.to_scirpy` is just calling scirpy code?
> 

That's right. A small update on this - the issue seems to lie in:

```python
# works ok
irdata = ddl.to_scirpy(vdj)
vdj2 = ir.io.to_dandelion(irdata)

# same issue with ValidationError: field productive has invalid bool T + T appears
irdata = ddl.to_scirpy(vdj, transfer = True)
vdj2 = ir.io.to_dandelion(irdata)
```

**Comment by zktuong** [comment]
ok. the 'issue' is with line 273:
https://github.com/scverse/scirpy/blob/2c5b99e7c5205adc506a10d1aca97250051fab81/scirpy/io/_datastructures.py#L260-L273

because dandelion's `productive` column in the metadata will update the `productive` key that scirpy was making from `to_airr_cells` because it appears later
https://github.com/scverse/scirpy/blob/2c5b99e7c5205adc506a10d1aca97250051fab81/scirpy/io/_io.py#L726-L739

Can confirm that if just change the name away from `productive` on dandelion's side, it resolves this. 

@sbenjamaporn if you just rename the current `productive` column to `productive_status`:
```
adata.obs.rename(columns={'productive':'productive_status'}, inplace=True)
```
you should be able to do the transfer.

I will action this on dandelion's side to rename `productive` to `productive_status`.

**Comment by sbenjamaporn** [comment]
@zktuong  Thanks, It works now!.

I have a more question during update germline sequence by update_germline. I have many samples to update. Should the fasta file be "tigger_heavy_igblast_db-pass_genotype.fasta" ? ( I also got the error in this case) or manually specify in each sample ?

**OSError: Environmental variable GERMLINE must be set. Otherwise, please provide path to folder containing germline IGHV, IGHD, and IGHJ fasta files.**

**Comment by grst** [comment]
Thanks a lot @zktuong! LMK once you have a release including the fix, then I'll pin the latest version of dandelion.

**Comment by zktuong** [comment]
> @zktuong Thanks, It works now!.
> 
> I have a more question during update germline sequence by update_germline. I have many samples to update. Should the fasta file be "tigger_heavy_igblast_db-pass_genotype.fasta" ? ( I also got the error in this case) or manually specify in each sample ?
> 
> **OSError: Environmental variable GERMLINE must be set. Otherwise, please provide path to folder containing germline IGHV, IGHD, and IGHJ fasta files.**

Let's follow up over on dandelion's side:
https://github.com/zktuong/dandelion/issues/153

**Comment by zktuong** [comment]
Hi @grst,

i've just release [sc-dandelion==0.2.3](https://pypi.org/project/sc-dandelion/0.2.3/) (it's actually 0.2.2 but i thought my upload went wrong)
Need to wait for https://github.com/pypa/warehouse/issues/11696 to be fixed before making any changes here though... =(
