### ISSUE TITLE
Error in loading filtered_contig_annotations.csv

### ISSUE THREAD

**Issue by france-hub** [scverse/scirpy#363]
### Description of the bug

Hello! I just started using python and scirpy. I have been using R for scRNAseq analysis but I am interested on the query epitope databases step of your tutorial. 
The problem is that I don't think the loading and merging of the filtered_contig_annotations.csv with the adata work (please see the attached figure). The filtered_contig_annotations.csv work in R when I merge them with a seurat object.
![Figure_1](https://user-images.githubusercontent.com/56587709/189538208-b7ae1cb5-e6c6-484d-a90e-d465cc562e05.png)

I tried to read in each file and then concatenate (look at the code below). It does not work even when I try to merge one csv file with adata. 'bas219.csv', 'bas229.csv',... are my renamed  filtered_contig_annotations.csv.
What would you check to understand where the error is?

Thanks!

### Minimal reproducible example

```python
filenames = ['bas219.csv', 'bas229.csv', 'bas264.csv', 'basV03.csv', 'basV09.csv', 'post219.csv', 'post229.csv', 'post264.csv', 'postV03.csv', 'postV09.csv']
tcrs = [ir.io.read_10x_vdj(filename) for filename in filenames]
tcr = tcrs[0].concatenate(tcrs[1:])

ir.pp.merge_with_ir(adata, tcr)
```

### Version information

```txt
sc.logging.print_versions()
-----
anndata     0.8.0
scanpy      1.9.1
-----
Levenshtein                 NA
PIL                         9.2.0
adjustText                  NA
airr                        1.4.1
beta_ufunc                  NA
binom_ufunc                 NA
console_thrift              NA
cycler                      0.10.0
cython_runtime              NA
dateutil                    2.8.2
h5py                        3.7.0
hypergeom_ufunc             NA
igraph                      0.10.0
joblib                      1.1.0
kiwisolver                  1.4.4
llvmlite                    0.39.1
matplotlib                  3.5.3
mpl_toolkits                NA
natsort                     8.2.0
nbinom_ufunc                NA
ncf_ufunc                   NA
networkx                    2.8.6
numba                       0.56.2
numpy                       1.23.2
packaging                   21.3
pandas                      1.4.4
parasail                    1.3.3
pkg_resources               NA
pydev_console               NA
pydev_ipython               NA
pydevconsole                NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pyparsing                   3.0.9
pytz                        2022.2.1
scipy                       1.9.1
scirpy                      0.11.1
scvelo                      0.2.4
seaborn                     0.12.0
session_info                1.0.0
setuptools_scm              NA
sitecustomize               NA
six                         1.16.0
sklearn                     1.1.2
statsmodels                 0.13.2
texttable                   1.6.4
threadpoolctl               3.1.0
tqdm                        4.64.1
tracerlib                   NA
typing_extensions           NA
yaml                        6.0
yamlordereddictloader       NA
zipp                        NA
-----
Python 3.8.14 (default, Sep  8 2022, 00:02:10) [GCC 7.5.0]
Linux-5.4.0-125-generic-x86_64-with-glibc2.27
```

**Comment by grst** [comment]
I would suspect that the `adata.obs_names` are not consistent with `tcr.obs_names`. Can you double-check that?

If this is not the problem, the first thing I'd verify if that the import of the csv files was successful. For instance by running `chain_qc` on the unmerged tcr object.

**Comment by france-hub** [comment]
Yes, the obs_names were different and I think I fixed it. I still have some issues with the downstream analysis, but it's not a package issue for sure. I am a python newbie, 

Thanks for your help!
