### ISSUE TITLE
incomplete `airr` format

### ISSUE THREAD

**Issue by zktuong** [scverse/scirpy#405]
I'm finding myself trying to read in some incomplete/imperfect rearrangement files and was wondering if you are opposed to change:
https://github.com/scverse/scirpy/blob/ca94aeffce0ae4142064b0d103ae48303bba9e1b/scirpy/io/_io.py#L464-L466

to:
```python
for chain_dict in iterator:
    cell_id = chain_dict.pop("cell_id")
    chain_dict.update(
        {req: "" for req in RearrangementSchema.required if req not in chain_dict}
    )
```

**Comment by grst** [comment]
I guess this makes sense... But the null token should be `None` not `""`.

**Comment by zktuong** [comment]
OK i can put in a PR for this!
