### ISSUE TITLE
module 'scirpy.pp' has no attribute 'index_chains'

### ISSUE THREAD

**Issue by xuezhang335** [scverse/scirpy#416]
Hi @grst,
When I used the ir.pp.index_chians, met the error: module 'scirpy.pp' has no attribute 'index_chains'. 
It seems that there is no function: ir.pp.index_chians. The version of scirpy is 0.12.2. Am I missing something?

`>>> dir(ir.pp)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_merge_adata', 'deprecated', 'ir_dist', 'ir_neighbors', 'merge_airr_chains', 'merge_with_ir', 'merge_with_tcr', 'tcr_neighbors']
`

Thanks very much,
Zhang

**Comment by grst** [comment]
Sorry for the confusion. The documentation on https://scirpy.scverse.org/en/latest/ already points to the docs for v0.13 in which significant changes were introduced. 

The latest stable release is still v0.12.2. 

I will release v0.13 within the next days. 

You can upgrade to the pre-release of v0.13 already using 
```
pip install --pre --upgrade scirpy
```

alternatively, you'll find the documentation for v0.12 here: https://scverse.org/scirpy/tags/v0.12.0/index.html

(I'd recommend you go for the v0.13 already - support for v0.12 will end soon -- I'm happy to help with any issues you have with the new version).

**Comment by grst** [comment]
v0.13 is now released and available from PyPI. 

I'm closing this issue for now, let me know if there are other problems!
