### ISSUE TITLE
Pandas is still pinned to 1.5.3 when installing Scirpy 13.0 with conda/mamba

### ISSUE THREAD

**Issue by a-munoz-rojas** [scverse/scirpy#426]
**Describe the bug**
I am setting up a new environment to try out the new scirpy v13.0 with the updated AIRR and awkward array formats. When I install Scirpy using conda/mamba, I noticed that it downgrades my pandas to 1.5.3. Not a big issue, but I noticed in the commits for the 13.0 release that the pandas should be unpinned and compatible with 2.0 (#410) so I wanted to report it.

**To Reproduce**
`mamba install -c conda-forge -c bioconda scirpy`
or 
`conda install -c conda-forge -c bioconda scirpy=0.13`

**Expected behaviour**
Should install pandas 2.0 

**System**

-   OS: macOS 12.6.7
-   Python 3.10
-   Versions of libraries involved: AnnData 0.9.1, Scirpy 0.13.0]

**Additional context**

**Comment by grst** [comment]
Thanks for reporting, I indeed forgot to unpin the pandas version in the bioconda recipe 1

**Comment by grst** [comment]
should be fixed now.
