### ISSUE TITLE
Incorporating uns['clone_id']['cell_indices'] as an obs column

### ISSUE THREAD

**Issue by Ngort** [scverse/scirpy#431]
(I think, based on delving further, that this constitutes more of a feature request than a bug report)
**Describe the bug**
ir.tl.define_clonotypes leads to clone_id definitions that differ between the obs columns and the uns keys. Cell indices in the uns don't match those of the obs column. It seems that obs is clustering the uns clonotypes that are quite different from each other.

EDIT: I now understand they're MEANT to be different. That said, why aren't cell_indices incorporated as a column? i.e. "unique_receptor_id" or something like that?

**To Reproduce**

```
ir.tl.chain_qc(mdata, airr_mod='tcr')

ir.pp.ir_dist(mdata, airr_mod='tcr', metric="identity", sequence='nt', n_jobs=4, )

ir.tl.define_clonotypes(mdata, airr_mod='tcr',
                        n_jobs=4, same_v_gene='all', dual_ir='all', 
                        within_group=['receptor_type', 'donor_id_demux'])

```

To see how clone_id from obs and clone_id from uns match or not:

```
cell_indices = mdata['tcr'].uns['clone_id']['cell_indices']
cell_indices = (v, k) for k, values in cell_indices.items() for v in values]

clones_dif = pd.DataFrame(cell_indices, columns=['', 'clone_id_uns']).set_index('').join(mdata['tcr'].obs['clone_id'])

dict_indices = clones_dif.groupby('clone_id')['clone_id_uns'].apply(set).to_dict()
dict_indices = dict(sorted(list(dict_indices.items()), key=lambda x : int(x[0])))
```
shows split clonotypes in uns:

`
{'0': {'0'},
 '1': {'1'},
 '2': {'2'},
 '3': {'3'},
 '4': {'4'},
 '5': {'5'},
 '6': {'6'},
 '7': {'7'},
 '8': {'8'},
 '9': {'9'},
 '10': {'10'},
 '11': {'11'},
 '12': {'12', '32'},
 '13': {'13'},
 '14': {'14'},
 '15': {'1367', '15'},
`
and as a consequence:

```
mdata['tcr'].uns['clone_id']['cell_indices']['1367']
>>> array(['BRI-2081-CTAAGACAGGACAGCT'], dtype=object)

mdata['tcr'][mdata['tcr'].obs['clone_id'] == '15'].obs_names
>>> Index(['BRI-2081-AAACGGGCATCACCCT', 'BRI-2081-CTAAGACAGGACAGCT'], dtype='object')
```
i.e. the cell `BRI-2081-CTAAGACAGGACAGCT` belongs to clonotype 15 according to the obs, but to clonotype 1367 according to the uns. These clonotypes seem to be quite different:

![image](https://github.com/scverse/scirpy/assets/13844936/abc0e50e-bf36-4f7f-8edd-0facaf9ed652)

This behavior remains no matter what parameters I use on `define_clonotypes`. The number of uns keys is always slightly larger than the number of obs categoricals.

**Expected behaviour**
I would expect the cell_indices dictionary within uns['clone_id'] to match those of the obs column.

**System**

-   OS: Linux
-   Python version 3.9.16
-   Versions of libraries involved [Muon 0.1.5, Scirpy 0.13.0, Scanpy 1.9.3]

**Comment by grst** [comment]
Hi @Ngort, 

thanks for opening this issue! 

> EDIT: I now understand they're MEANT to be different. That said, why aren't cell_indices incorporated as a column? i.e. "unique_receptor_id" or something like that?

Yes, the index from `uns` refers to a temporary data frame of unique receptor configurations. 
So far, I didn't include them in `obs` because I didn't see a use-case for that and thought the additional column would just confuse users. Could you elaborate why you need them?

**Comment by grst** [comment]
@Ngort, can this be closed?

**Comment by Ngort** [comment]
Yes, I think it was well addressed. Thank you.
