### ISSUE TITLE
Error associating clonotype abundance/expansion with clusters

### ISSUE THREAD

**Issue by leeanapeters** [scverse/scirpy#441]
Hi, thank you for the great package! This is my first time using muondata objects for joint gex and tcr analysis and I am having some trouble grouping by cluster and plotting abundance.

**To Reproduce**
I followed the scirpy tutorial through concatenation but then ran harmony to batch correct my data and ran leiden clustering prior to creating the muondata object with RNA and tcr.

I am having an issue where I am not able to plot gene expression alongside observations in the airr modality.

The first error was a key error saying that leiden is not present in .obs or .vars even though leiden is present in .obs. I think I corrected this by running leiden on the concatenated and batch corrected anndata object first and then remaking the muondata object.

However the next error when I try to use scirpy functions to plot observations and data from both the gex and airr modalities is "AttributeError: 'DataFrame' object has no attribute '_convert'". I am not sure what this means. See error and code below. This is true for any functions from scirpy which call obs from both gex and airr. 

```python
_ = ir.pl.group_abundance(
    mdata, groupby="airr:is_convergent", target_col="gex:sample", max_cols=15, figsize=(5, 3)
)
```

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/scirpy/pl/_group_abundance.py", line 98, in group_abundance
    return base.bar(abundance, **kwargs)
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/scirpy/pl/base.py", line 67, in bar
    # Remove excess x label
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/plotting/_core.py", line 1136, in bar
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/plotting/_core.py", line 975, in __call__
    label_kw = kwargs["label"] if "label" in kwargs else False
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 450, in generate
    self._compute_plot_data()
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/plotting/_matplotlib/core.py", line 608, in _compute_plot_data
    data = data._convert(datetime=True, timedelta=True)
  File "/orange/brusko/leeanapeters/RIMA/miniconda3/envs/scirpy/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    -------
AttributeError: 'DataFrame' object has no attribute '_convert'
```

I know that clone_id is present, as well as is_convergent, and sample in the gex modality.

Any help would be much appreciated!

### Session info

```
anndata             0.9.2
matplotlib          3.7.2
mudata              0.2.3
muon                0.1.5
pandas              2.0.3
scanpy              1.9.3
scirpy              0.13.0
session_info        1.0.0
-----
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:55:59) [GCC 12.3.0]
Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.35
```

**Comment by grst** [comment]
Hi @leeanapeters, 

thanks for reporting the issue!

It seems the `._convert()` method was removed in pandas 2.0 (see https://github.com/pandas-dev/pandas/pull/50026)

I come to suspect that somehow your environment is broken, because pandas 2.0.3 (as per your session info) doesn't have the `_convert()` call in line 608 of `_matplotlib/core.py`: 
https://github.com/pandas-dev/pandas/blob/0f437949513225922d851e9581723d82120684a6/pandas/plotting/_matplotlib/core.py#L608

Maybe you could try starting with a new venv/conda env from scratch? 

---

Regarding the `leiden` key missing from your object: You need to be aware that `mdata.obs` is independent from `mdata['gex'].obs` and `mdata['airr'].obs`. You can synchronize them by calling `mdata.update()`. When re-creating the mdata object, `.update()` is called implicitly, which is probably why this worked for you. 

Hope this helps, 
Gregor

**Comment by leeanapeters** [comment]
Thank you so much for the quick reply!

Both of those sizes got rid of those errors :)


I do have another question though:

Should I subset my object before performing clonotype modularity? I am getting the length error that was previously reported in #302


Thanks!


Leeana

**Comment by grst** [comment]
> Should I subset my object before performing clonotype modularity? I am getting the length error that was previously reported in https://github.com/scverse/scirpy/issues/302

That should't be nescessary! As mentioned in the comment there, it would be great if you could open a separate issue with the full error message that I can investigate :)

**Comment by grst** [comment]
Closing this as the original issue is solved.
