### ISSUE TITLE
Epitope database query error

### ISSUE THREAD

**Issue by andrewjkwok** [scverse/scirpy#448]
**Describe the bug**
When trying to run the command:

`ir.pp.ir_dist(mdata, vdjdb, metric="identity", sequence="aa")`

I receive an error showing:
```
ValueError: No AIRR data found in adata.obsm['airr']. Your AnnData object might be using an outdated schema. Scirpy has updated the format of `adata` in v0.13. AIRR data is now stored as an awkward array in `adata.obsm['airr']`.Please run `ir.io.upgrade_schema(adata) to update your AnnData object to the latest version. 
```

When I try to run the `ir.io.upgrade_schema` command as suggested, I nonetheless get:
`ValueError: Your AnnData object seems already up-to-date with scirpy v0.13`, no matter whether I run
`ir.io.upgrade_schema(mdata['airr'])` or `ir.io.upgrade_schema(mdata)`

**To Reproduce**
Very happy to share data if needed for this if I could have an email address I could share a google drive link?

**System**
- Python 3.10
- Versions of libraries involved [e.g. AnnData 0.8.0, Scirpy 0.12.0]
```
scanpy==1.9.3 
anndata==0.9.2 
scirpy==0.13.0
muon==0.1.5
```

Please let me know if there is anything else I could provide to help debug/troubleshoot, thank you.

**Comment by grst** [comment]
Hi, 

I think this might be the same issue as answered here: https://discourse.scverse.org/t/problems-with-querying-reference-databases-or-datasets-for-annotation-of-irs/1564

LMK if this doesn't work for you!

**Comment by grst** [comment]
Closing this for now, let me know if this is still an issue!
