### ISSUE TITLE
If integer field is None, writing AIRR files fails 

### ISSUE THREAD

**Issue by nathaniel-tcypher** [scverse/scirpy#454]
**Describe the bug**
If there are any fields that are None (e.g. d_sequence_end for alpha chains), then the **io.write_airr** method fails with:

`
File ".venv/lib/python3.10/site-packages/scirpy/io/_io.py", line 589, in write_airr
    chain[f] = int(chain[f])
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
`

**To Reproduce**
Load in any AIRR file with mixed TRA/TRB chains and try to write it back out again. 

>data = ir.io.read_airr(airr_path)
>ir.io.write_airr(data, 'output_airr.tsv')   

**Expected behaviour**
File should be written out without errors.

**System**

-   OS: MacOSX
-   Python version 3.10
-   Versions of libraries involved: Scirpy 0.13.1

**Additional context**
I'd imagine it's this bit:

<img width="825" alt="image" src="https://github.com/scverse/scirpy/assets/128479646/939e2025-6efc-4fbd-9f42-f01099ae9d6f">

**Comment by grst** [comment]
Good catch, thanks for reporting! I'll address this in the next release.
