### ISSUE TITLE
Unclear default value for the Hamming Distance cut-off

### ISSUE THREAD

**Issue by FFinotello** [scverse/scirpy#471]
Hi @grst!

I think it is not clear from the [API documentation of the HammingDistanceCalculator](https://scirpy.scverse.org/en/latest/generated/scirpy.ir_dist.metrics.HammingDistanceCalculator.html#scirpy.ir_dist.metrics.HammingDistanceCalculator) whether the default of the `cutoff` parameter is `None` or `2`:

<img width="646" alt="image" src="https://github.com/scverse/scirpy/assets/24915818/7f61fea6-34eb-49c4-b6d1-177ab98e9936">

**Comment by grst** [comment]
Good catch! Actually both is true -- `cutoff=None` is the default value, but if `cutoff is None`, a default of 2 is selected. 
Clearly the documentation needs to be improved.
