### ISSUE TITLE
Where has UMI count for AIR chains gone?

### ISSUE THREAD

**Issue by adamwoolfe** [scverse/scirpy#478]
**Describe the bug**
I am looking to access UMI count for each chain of a set of antibodies read into the scirpy anndata frame. It appears that **read count** is present in the awkward array associated with the airr anndata obsm awkward array under the title 'consensus_count' like so:

adata["airr"].obsm['airr']['consensus_count']

but the UMI count is nowhere to be found. None of the available fields point to the UMI count.

where has this field gone (it is present in the original 10X filtered_contig_annotation.csv input file)?

**System**

-   OS: Linux
-   Python version: 3.10.3
-   Versions of libraries:
anndata             0.10.4
awkward             2.5.1
matplotlib          3.8.2
mudata              0.2.3
muon                0.1.5
numpy               1.26.2
pandas              2.1.3
scanpy              1.9.3
scirpy              0.14.0

**Additional context**

**Comment by grst** [comment]
Hi Adam, 

thanks for bringing this up! 
The UMI count goes to `adata["airr"].obsm["airr"]["duplicate_count"]`. 

I always found this a bit confusing, and I've just seen that [there has been an update to the AIRR Rearrangement standard](https://docs.airr-community.org/en/latest/news.html#version-1-5-0-august-29-2023) that introduces a dedicated `umi_count` field which is a lot clearer. I'll update scirpy to use this field instead in the future. 

Best, 
Gregor
