### ISSUE TITLE
 TypeError: join() got an unexpected keyword argument 'validate'

### ISSUE THREAD

**Issue by 1w2y3x6078** [scverse/scirpy#522]
Hi,

I keep getting an error " TypeError: join() got an unexpected keyword argument 'validate'" How should I continue?

thanks,
Morgan
samples = {
...     "C144": {"group": "mild"},
...     "C146": {"group": "severe"},
...     "C149": {"group": "healthy control"},
... }
>>> adatas_tcr = {}
>>> adatas_gex = {}
>>> for sample in samples.keys():
...     gex_file = glob(f"/mnt/icfs/work/singlecellproject/personal/wangyanxin/scirpy/data/GSE145926_RAW/*{sample}*.h5")[0]
...     tcr_file = glob(f"/mnt/icfs/work/singlecellproject/personal/wangyanxin/scirpy/data/GSE145926_RAW/*{sample}*.csv.gz")[0]
...     adata_gex = sc.read_10x_h5(gex_file)
...     adata_tcr = ir.io.read_10x_vdj(tcr_file)
...     # concatenation only works with unique gene names
...     adata_gex.var_names_make_unique()
...     adatas_tcr[sample] = adata_tcr
...     adatas_gex[sample] = adata_gex
... 
/mnt/icfs/work/singlecellproject/.local/lib/python3.9/site-packages/anndata/_core/anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

/mnt/icfs/work/singlecellproject/.local/lib/python3.9/site-packages/anndata/utils.py:334: ExperimentalFeatureWarning: Support for Awkward Arrays is currently experimental. Behavior may change in the future. Please report any issues you may encounter!
  warnings.warn(msg, category, stacklevel=stacklevel)
/mnt/icfs/work/singlecellproject/.local/lib/python3.9/site-packages/anndata/_core/anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/mnt/icfs/work/singlecellproject/.local/lib/python3.9/site-packages/anndata/_core/anndata.py:1820: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
WARNING: Non-standard locus name: Multi 
>>> 
>>> adata_gex = anndata.concat(adatas_gex, index_unique="_")
>>> adata_tcr = anndata.concat(adatas_tcr, index_unique="_")
>>> mdata = mu.MuData({"gex": adata_gex, "airr": adata_tcr})
>>> mdata.obs["sample"] = mdata.obs_names.to_series().str.split("_", expand=True)[1]
>>> mdata.obs["group"] = mdata.obs["sample"].map(lambda x: samples[x]["group"])
>>> mdata
MuData object with n_obs × n_vars = 10715 × 33539
  obs:	'sample', 'group'
  2 modalities
    gex:	10706 x 33539
    airr:	581 x 0
      obsm:	'airr'
>>> sc.pp.log1p(mdata["gex"])
>>> sc.pp.pca(mdata["gex"], svd_solver="arpack")
>>> sc.pp.neighbors(mdata["gex"])
>>> sc.tl.umap(mdata["gex"])
>>> ir.pp.index_chains(mdata)
>>> ir.tl.chain_qc(mdata)
>>> fig, (ax0, ax1, ax2) = plt.subplots(1, 3, figsize=(15, 4), gridspec_kw={"wspace": 0.5})
mdata, basis="gex:umap", color="airr:receptor_type", ax=ax2)>>> mu.pl.embedding(mdata, basis="gex:umap", color="CD3E", ax=ax0, show=False)
<Axes: title={'center': 'CD3E'}, xlabel='X_umap1', ylabel='X_umap2'>
>>> mu.pl.embedding(mdata, basis="gex:umap", color="sample", ax=ax1, show=False)
<Axes: title={'center': 'sample'}, xlabel='X_umap1', ylabel='X_umap2'>
>>> mu.pl.embedding(mdata, basis="gex:umap", color="airr:receptor_type", ax=ax2)
>>> fig.savefig("/mnt/icfs/work/singlecellproject/personal/wangyanxin/scirpy/plotsubplots.png")
>>> sc.pp.filter_genes(mdata["gex"], min_cells=10)
>>> sc.pp.filter_cells(mdata["gex"], min_genes=100)
>>> mdata.update()
ir.tl.define_clonotypes(mdata, receptor_arms="all", dual_ir="primary_only")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/icfs/work/singlecelldevelopment/miniconda3/envs/CytoTRACE/lib/python3.9/site-packages/scirpy/tl/_clonotypes.py", line 396, in define_clonotypes
    return define_clonotype_clusters(
  File "/mnt/icfs/work/singlecelldevelopment/miniconda3/envs/CytoTRACE/lib/python3.9/site-packages/scirpy/tl/_clonotypes.py", line 287, in define_clonotype_clusters
    ctn = ClonotypeNeighbors(
  File "/mnt/icfs/work/singlecelldevelopment/miniconda3/envs/CytoTRACE/lib/python3.9/site-packages/scirpy/ir_dist/_clonotype_neighbors.py", line 52, in __init__
    self.cell_indices, self.clonotypes = self._make_clonotype_table(params)
  File "/mnt/icfs/work/singlecelldevelopment/miniconda3/envs/CytoTRACE/lib/python3.9/site-packages/scirpy/ir_dist/_clonotype_neighbors.py", line 79, in _make_clonotype_table
    obs = obs.join(
TypeError: join() got an unexpected keyword argument 'validate'

**Comment by grst** [comment]
What's your pandas version?

**Comment by 1w2y3x6078** [comment]
scanpy==1.10.1 anndata==0.10.7 umap==0.5.6 numpy==1.26.4 scipy==1.13.0 pandas==1.3.5 scikit-learn==1.4.2 statsmodels==0.14.2 igraph==0.11.4 pynndescent==0.5.12

**Comment by 1w2y3x6078** [comment]
Thank you for replying so quickly

**Comment by grst** [comment]
You need at least pandas>1.5. No idea how you ended up with this environment, because this is defined in the scirpy dependencies.

**Comment by 1w2y3x6078** [comment]
Thank you

**Comment by 1w2y3x6078** [comment]
Hello, I still need to ask you a question. I have conducted aggr merge analysis on the data of more than 10x samples. Can I directly input the h5 after 10xaggr merge and the csv after immunization merge

**Comment by 1w2y3x6078** [comment]
Is the result different from the result of entering 10X many single samples separately

**Comment by grst** [comment]
Not sure if I get your question, but it should not matter if you merge VDJ and gene expression data first and then concatenate multiple samples, or if you first build individual objects for VDJ and gene expression and merge them at the end. 

There's a section in the IO tutorial about combining multiple samples: https://scirpy.scverse.org/en/latest/tutorials/tutorial_io.html#combining-multiple-samples

**Comment by grst** [comment]
Closing this, as the original issue has been resolved. For support requests (rather than bug reports), it's better to post on the [scverse discourse](https://discourse.scverse.org/).
