### ISSUE TITLE
Thoughts on adding motif results to amino acid similarity?

### ISSUE THREAD

**Issue by n-hal** [scverse/scirpy#530]
I.e. in when clustering TCRs on amino-acid similarity it might be nice to return a string that encapsulates the conserved sequence, with a wild-card character (maybe %D:N, for example suggesting that substitutions between D:N in the blosum matrix would be tolerated in this group).

If this is of any interest I would be happy to contribute to it.

**Comment by grst** [comment]
Hi @n-hal, 

in principle this is of interest. Could you elaborate whot that string would look like?

There's a long-standing request to add sequence logos #12 which might go into the same direction?

**Comment by grst** [comment]
Closing this in favor of #12. If you need anyting in addition to sequence logos, please let me know and we can discuss it.
