### ISSUE TITLE
ir.pl.clonotype_network

### ISSUE THREAD

**Issue by 1w2y3x6078** [scverse/scirpy#531]
>>> mdata
MuData object with n_obs × n_vars = 40797 × 25566
  obs:	'sample', 'stim', 'cluster'
  uns:	'stim_colors', 'sample_colors'
  2 modalities
    gex:	40359 x 25566
      obs:	'sample', 'stim', 'cluster'
      var:	'gene_ids', 'feature_types'
      uns:	'log1p', 'pca', 'neighbors', 'umap', 'airr:chain_pairing_colors', 'airr:clonal_expansion_colors', 'airr:receptor_type_colors'
      obsm:	'X_pca', 'X_umap'
      varm:	'PCs'
      obsp:	'distances', 'connectivities'
    airr:	16772 x 0
      obs:	'receptor_type', 'receptor_subtype', 'chain_pairing', 'clone_id', 'clone_id_size', 'clonal_expansion'
      uns:	'scirpy_version', 'chain_indices', 'ir_dist_nt_identity', 'clone_id', 'ir_dist_aa_alignment', 'clonotype_network'
      obsm:	'airr', 'chain_indices', 'X_clonotype_network'
ir.pl.clonotype_network(mdata, color="sample", base_size=10, label_fontsize=7, panel_size=(7, 7), airr_mod='airr')画图的时候出现NaN怎样删除

**Comment by 1w2y3x6078** [comment]
The resulting graph looks like this. How do we remove nan, and why do we have so many nan

Thank you for your help

**Comment by grst** [comment]
Sorry, I can't see your example image. 
Likely the NAs are cells without at TCR.

**Comment by grst** [comment]
If you have any usage questions, please use the scverse discourse: https://discourse.scverse.org
