### ISSUE TITLE
Error with define_clonotypes on small datasets

### ISSUE THREAD

**Issue by leuschjanphilipp** [scverse/scirpy#533]
Dear scirpy team, I'm reporting an issue that has popped up a few times in our repo [mvTCR](https://github.com/SchubertLab/mvTCR): [here](https://github.com/SchubertLab/mvTCR/issues/15) and [here](https://github.com/SchubertLab/mvTCR/issues/18)

**Describe the bug**
We've been encountering a `TypeError: iteration over a 0-d array` error when using `scirpy.tl.define_clonotypes` on smaller datasets. The error seems to stem from how clonotype distances are calculated and aggregated under certain conditions.

**To Reproduce**
Additional information such as full error codes can be found in the referenced issues above. If you want to directly reproduce:
- `conda create --name mvTCR python=3.10 -y && conda activate mvTCR && pip install mvtcr==0.2.1 && conda install nb_conda_kernels -y` (important that mvtcr v0.2.1 is used because there is a fix in the newest version)
- Download and follow the tutorials [00_10x_data_preprocessing.ipynb](https://github.com/SchubertLab/mvTCR/blob/master/tutorials/00_10x_data_preprocessing.ipynb) to generate the data and [01_preprocessing.ipynb](https://github.com/SchubertLab/mvTCR/blob/master/tutorials/01_preprocessing.ipynb) to encounter the bug.
- In tutorial 01_preprocessing in cell 3 switch `selected_patients = ['AP1', 'CV0062']` to `selected_patients = ['AP1']` (downsampling to only one patient aka a small dataset)
- Follow along and cell 11 should then fail with the error as well as cell 13 (which do the same thing)

In one of our issues someone encountered the same issue on a different dataset.

**Additional context/information**
The error occurs when the dataset for computing clonotypes is too small. Specifically, under this condition:
`if self.n_jobs == 1 or n_clonotypes <= 2 * self.chunksize` (your_env\Lib\site-packages\scirpy\ir_dist\ _clonotype_neighbors.py line 213, see error traces in the issues on how to get there)
If this condition is true, scirpy calculates distances for clonotypes in a single process and returns them as a generator object, which cannot be stacked by scipy.sparse.vstack. This results in the error: `TypeError: iteration over a 0-d array.`
However, when the dataset (n_clonotypes) is large enough and the condition is false, distances are computed using multi-processing and returned as a list, which can be properly stacked by scipy.sparse.vstack.

For me, it worked when casting the row distances as a list again:
`dist_rows = tqdm(
                list(self._dist_for_clonotype(i) for i in range(n_clonotypes)),
                total=n_clonotypes,
            )`
(row 214-17)

As a temporary hack, we set the chunksize to 1 in the define_clonotypes function to force the condition to evaluate as false, bypassing the bug even when working with small datasets. However, it would be great if you could verify whether this is indeed a bug on your end and potentially roll out a fix.

Cheers & thanks,
Jan

**Comment by grst** [comment]
Thanks for the detailled analysis! I'll try to patch this within the next week.

**Comment by grst** [comment]
Hi Jan, 

where can I find the data from your preprocessing tutorial? 
```
path_base = '../data/10x_CD8TC/raw/'
```

Which version of scirpy are you testing? I tried looking into the code section you are describing, but both branches are covered by test cases and the result is explicitly casted to a list before it is vstacked: 
```python
dist = sp.vstack(list(dist_rows))
```

**Comment by leuschjanphilipp** [comment]
Hi thanks for the quick reply! The dataset can be downloaded from the [10x website ](https://www.10xgenomics.com/resources/datasets)under and the keywords "a new way immune profiling". 

We are still running on scirpy v0.13.1, where this is an issue, but as you pointed out, it is not with the current version. Sorry to steal your time in this manner...

**Comment by grst** [comment]
No worries :)
