### ISSUE TITLE
 ir.pl.clonotype_network doesn't use the right obsm entry

### ISSUE THREAD

**Issue by LinearParadox** [scverse/scirpy#543]
**Describe the bug**
When using  ir.pl.clonotype_network with a custom key, the correct uns entry is chosen, however it does not apply this to obsm. It will still use 'X_clonotype_network' by default and throw an error.
**To Reproduce**
run
```
ir.tl.clonotype_network
```
with a custom key added.
Attempt to plot it using 
```
ir.pl.clonotype_network(
```

**Expected behaviour**
Using X_{key_name}

As a followup:

this seems tied to:
```
_graph_from_coordinates(params.adata, clonotype_key)
```
using:
cast(pd.DataFrame, adata.obsm["X_clonotype_network"])...
instead of:
cast(pd.DataFrame, adata.obsm[f"X_{clonotype_key}"])...

**Comment by grst** [comment]
Thanks for reporting! 

Should be fixed in #545 -- It should now work to specify `ir.pl.clonotype_network(basis = XXX, ...)`. 

Would be great if you could give it a try with
```
pip install git+https://github.com/scverse/scirpy.git@fix-543
```
