### ISSUE TITLE
scirpy.datasets.vdjdb doesn't work anymore

### ISSUE THREAD

**Issue by ancooley** [scverse/scirpy#575]
This function is no longer working as expected:
![Image](https://github.com/user-attachments/assets/8a01f9a5-195b-4daa-b475-e0b6e3751e46)
![Image](https://github.com/user-attachments/assets/4b69d0a0-3095-42aa-b2e0-24522d856cab)
![Image](https://github.com/user-attachments/assets/a6cc3471-7f80-49b2-8f57-4d5f36f5fca7)

**Comment by grst** [comment]
I also got the email notification from the cron on the scirpy repo... 
Apparently vdjdb changed their format, I'll look into it in the next days.
