### ISSUE TITLE
Integration Testing CI Test Failure on python 3.12

### ISSUE THREAD

**Issue by ilan-gold** [scverse/scirpy#577]
The daily CI failed on test for scirpy failed.  Please go to [the logs of the integration testing repo](https://github.com/scverse/integration-testing/actions/runs/12140798121) to review. @scverse/anndata

**Comment by grst** [comment]
@ilan-gold was this automatically posted? 
The tagged team seems off.
We also have @scverse-bot  as a system user  for which you can get API keys for automation.

**Comment by ilan-gold** [comment]
@grst hadn't noticed that it was coming from my account but even if I had, PAT seemed the only way to go.  Great to know about the bot, I will try to grab the PAT for it
